package resnyx.methods.chat;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import resnyx.TgMethod;
import resnyx.Types;

/**
 * Use this method to generate a new invite link for a chat; any previously generated link is revoked.
 * The bot must be an administrator in the chat for this to work and must have the appropriate admin rights.
 * Returns the new invite link as String on success.
 * <p>
 * Note: Each administrator in a chat generates their own invite links.
 * Bots can't use invite links generated by other administrators.
 * If you want your bot to work with invite links, it will need to generate its
 * own link using exportChatInviteLink – after this the link will become
 * available to the bot via the getChat method. If your bot needs to generate
 * a new invite link replacing its previous one, use exportChatInviteLink again.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
public final class ExportChatInviteLink extends TgMethod<String> {

    public static final String METHOD = "exportChatInviteLink";

    /**
     * Unique identifier for the target chat or username of the
     * target channel (in the format @channelusername)
     */
    @JsonProperty("chat_id")
    private Long chatId;

    public ExportChatInviteLink(String token, Long chatId) {
        super(token);
        this.chatId = chatId;
    }

    @Override
    protected String method() {
        return METHOD;
    }

    @Override
    protected TypeReference type() {
        return Types.STR;
    }
}
