language: java

jdk:
  - openjdk11

before_install:
  - ./gradlew --version
  - echo "artifactory_contextUrl=${AR_URL}" >> $HOME/.gradle/gradle.properties
  - echo "artifactory_user=${AR_USER}" >> $HOME/.gradle/gradle.properties
  - echo "artifactory_password=${AR_PASSWORD}" >> $HOME/.gradle/gradle.properties

deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file_glob: true
  file: "build/libs/*.jar"
  skip_cleanup: true
  on:
    tags: true

after_deploy:
  - ./gradlew build upload

notifications:
  email: false
  webhooks:
    urls:
      - https://resnyx.sergeybochkov.com/travis