language: java

jdk:
  - openjdk11

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper

before_install:
  - echo "artifactory_contextUrl=${AR_URL}" >> ~/.gradle/gradle.properties
  - echo "artifactory_user=${AR_USER}" >> ~/.gradle/gradle.properties
  - echo "artifactory_password=${AR_PASSWORD}" >> ~/.gradle/gradle.properties
  - echo "systemProp.sonar.host.url=${SONAR_HOST}" >> ~/.gradle/gradle.properties
  - echo "systemProp.sonar.login=${SONAR_LOGIN}" >> ~/.gradle/gradle.properties

deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file_glob: true
  file: "build/libs/*.jar"
  skip_cleanup: true
  on:
    tags: true

after_deploy:
  - ./gradlew build
  - ./gradlew sonarqube
  - ./gradlew artifactoryPublish

notifications:
  email: false
  webhooks:
    urls:
      - https://resnyx.sergeybochkov.com/travis