language: java

jdk:
  - openjdk11

before_install:
  - echo "artifactory_contextUrl=${AR_URL}" >> gradle.properties
  - echo "artifactory_user=${AR_USER}" >> gradle.properties
  - echo "artifactory_password=${AR_PASSWORD}" >> gradle.properties
  - echo "systemProp.sonar.host.url=${SONAR_HOST}" >> gradle.properties
  - echo "systemProp.sonar.login=${SONAR_LOGIN}" >> gradle.properties

deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file_glob: true
  file: "build/libs/*.jar"
  skip_cleanup: true
  on:
    tags: true

after_deploy:
  - ./gradlew clean build sonarqube artifactoryPublish